package yfcx123.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static yfcx123.domain.AssertUtils.zonedDataTimeSameInstant;

public class AccountInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountInfoAllPropertiesEquals(AccountInfo expected, AccountInfo actual) {
        assertAccountInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountInfoAllUpdatablePropertiesEquals(AccountInfo expected, AccountInfo actual) {
        assertAccountInfoUpdatableFieldsEquals(expected, actual);
        assertAccountInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountInfoAutoGeneratedPropertiesEquals(AccountInfo expected, AccountInfo actual) {
        assertThat(expected)
            .as("Verify AccountInfo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountInfoUpdatableFieldsEquals(AccountInfo expected, AccountInfo actual) {
        assertThat(expected)
            .as("Verify AccountInfo relevant properties")
            .satisfies(e -> assertThat(e.getAccountId()).as("check accountId").isEqualTo(actual.getAccountId()))
            .satisfies(e -> assertThat(e.getCompanyName()).as("check companyName").isEqualTo(actual.getCompanyName()))
            .satisfies(e -> assertThat(e.getSocialCreditCode()).as("check socialCreditCode").isEqualTo(actual.getSocialCreditCode()))
            .satisfies(e -> assertThat(e.getEntityLegalPerson()).as("check entityLegalPerson").isEqualTo(actual.getEntityLegalPerson()))
            .satisfies(e -> assertThat(e.getPassword()).as("check password").isEqualTo(actual.getPassword()))
            .satisfies(e -> assertThat(e.getFullyAddress()).as("check fullyAddress").isEqualTo(actual.getFullyAddress()))
            .satisfies(e -> assertThat(e.getCompanyContact()).as("check companyContact").isEqualTo(actual.getCompanyContact()))
            .satisfies(e -> assertThat(e.getMobileNumber()).as("check mobileNumber").isEqualTo(actual.getMobileNumber()))
            .satisfies(e -> assertThat(e.getAccountStatus()).as("check accountStatus").isEqualTo(actual.getAccountStatus()))
            .satisfies(e ->
                assertThat(e.getCreateTime())
                    .as("check createTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreateTime())
            )
            .satisfies(e ->
                assertThat(e.getUpdateTime())
                    .as("check updateTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdateTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountInfoUpdatableRelationshipsEquals(AccountInfo expected, AccountInfo actual) {
        // empty method
    }
}
